filebeat.inputs:
- type: http_endpoint
  enabled: true
  listen_address: 0.0.0.0
  listen_port: 5444
  response_code: 200
  response_body: '{"message": "success"}'
  url: "/"
  prefix: "json"
- type: syslog
  protocol.tcp:
    host: "0.0.0.0:5443"
  tags: ["json"]

processors:
  - add_locale:
      format: abbreviation
  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.type", "agent.version", "ecs.version", "input.type", "log.offset", "version"]



# logging.level: error
logging.level: ${FILEBEAT_LOG_LEVEL}
# ${FILEBEAT_LOG_LEVEL}

output.redis:
  hosts: ${REDIS_HOST}
  key: "logs-api"
  db: 0