version: "3.8"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data      
    networks:
      - app

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.3
    ports:
      - "5444:5444"    
      - "5443:5443"    
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    #   - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: filebeat
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      REDIS_HOST: redis
      FILEBEAT_LOG_LEVEL: info
      TZ: "America/Sao_Paulo"
    networks:
      - app
    command: -e -strict.perms=false -c /usr/share/filebeat/filebeat.yml

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    # ports:
    #   - "5601:5601"
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: logstash
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      REDIS_HOST: redis
    networks:
      - app

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      TZ: "America/Sao_Paulo"
    networks:
      - app

  elasticsearch:
    environment:
      discovery.type: single-node
      TZ: "America/Sao_Paulo"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"    
      - "9300:9300"  
    networks:
      - app      

volumes:
  elasticsearch-data:
  redis-data:
#   prometheus-data:
#   grafana_data:

networks:
  app:
    # driver: bridge
    # driver_opts:
      # encrypted: "true"
